services:
  postgres:
    image: postgres:16-alpine
    container_name: reachinbox_postgres
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox_secret
      POSTGRES_DB: reachinbox_scheduler
    ports:
      - '5432:5432'
    volumes:
      - reachinbox_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U reachinbox -d reachinbox_scheduler']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: reachinbox_redis
    ports:
      - '6379:6379'
    volumes:
      - reachinbox_redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: reachinbox_backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://reachinbox:reachinbox_secret@postgres:5432/reachinbox_scheduler?schema=public
      REDIS_URL: redis://redis:6379
      WORKER_CONCURRENCY: 5
      MIN_EMAIL_DELAY_MS: 2000
      MAX_EMAILS_PER_HOUR_PER_SENDER: 100
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_SECURE: 'false'
      SMTP_USER: 'dummy'
      SMTP_PASSWORD: 'dummy'
      SMTP_FROM: 'ReachInbox Scheduler <test@reachinbox.test>'
      JWT_SECRET: 'reachinbox-dev-secret-super-safe-123'
      GOOGLE_CLIENT_ID: 'dummy-client-id'
      GOOGLE_CLIENT_SECRET: 'dummy-client-secret'
      GOOGLE_CALLBACK_URL: 'http://localhost:3000/api/v1/auth/google/callback'
      FRONTEND_URL: 'http://localhost:8080'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: reachinbox_worker
    command: node dist/worker.js
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://reachinbox:reachinbox_secret@postgres:5432/reachinbox_scheduler?schema=public
      REDIS_URL: redis://redis:6379
      WORKER_CONCURRENCY: 5
      MIN_EMAIL_DELAY_MS: 2000
      MAX_EMAILS_PER_HOUR_PER_SENDER: 100
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_SECURE: 'false'
      SMTP_USER: 'dummy'
      SMTP_PASSWORD: 'dummy'
      SMTP_FROM: 'ReachInbox Scheduler <test@reachinbox.test>'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/api/v1
    container_name: reachinbox_frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  reachinbox_pg_data:
  reachinbox_redis_data:
